# -> CI/CD + DevSecOps Pipeline

trigger:
  - "*"

pr:
  - "*"

pool:
  vmImage: ubuntu-latest

variables:
  - group: url-shortener-secrets

stages:
  - stage: Build
    jobs:
      - job: BuildApp
        displayName: 'Build'
        steps:
          - template: templates/java-setup.yaml
          - task: Maven@4
            inputs:
              mavenPomFile: 'backend/pom.xml'
              goals: 'package'
              options: '-DskipTests'

  - stage: Test
    jobs:
      - job: RunUnitTests
        displayName: 'Unit tests'
        steps:
          - template: templates/java-setup.yaml
          - task: Maven@4
            inputs:
              mavenPomFile: 'backend/pom.xml'
              goals: 'test'
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/surefire-reports/*.xml'

  - stage: Quality_Security
    displayName: 'Quality & Security'
    jobs:
      - job: CheckStyleWithSpotless
        displayName: 'Check Style'
        steps:
          - template: templates/java-setup.yaml
          - task: Maven@4
            inputs:
              mavenPomFile: 'backend/pom.xml'
              goals: 'spotless:check'
      - job: CheckCodeQualityWithSonarCloud
        displayName: 'Check Code Quality'
        steps:
          - template: templates/java-setup.yaml
          - task: Maven@4
            inputs:
              mavenPomFile: 'backend/pom.xml'
              goals: 'sonar:sonar'
              options: '-Dsonar.token=$(SONAR_TOKEN)'
      - job: CheckDependenciesSecurityWithOWASP
        displayName: 'Check Dependencies'
        steps:
          - template: templates/java-setup.yaml
          - task: Cache@2
            inputs:
              key: 'owasp-db | $(Agent.OS)'
              path: '$(Pipeline.Workspace)/.m2/repository/org/owasp'
              cacheHitVar: 'OWASP_CACHE_HIT'
            continueOnError: true
          - task: Maven@4
            inputs:
              mavenPomFile: 'backend/pom.xml'
              goals: 'dependency-check:check'
              options: '-Dnvd.api.key=$(NVD_API_KEY) -DossindexAnalyzerEnabled=false -DfailOnError=false'

  - stage: Push
    condition: | 
      and(
        succeeded(),
        or(
          eq(variables['Build.SourceBranch'], 'refs/heads/main'),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        )
      )
    jobs:
      - job: PushToACR
        displayName: 'Push To ACR'
        steps:
          - task: Docker@2
            inputs:
              command: 'buildAndPush'
              repository: 'url-shortener'
              dockerfile: './backend/Dockerfile'
              containerRegistry: 'shortitacr'
              tags: |
                $(Build.SourceVersion)
                $(Build.SourceBranchName)
                latest
      - job: ScanImageWithTrivy
        displayName: 'Scan Image'
        dependsOn: PushToACR
        steps:
          - script: |
              docker login shortitacr.azurecr.io -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
              curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
              trivy image shortitacr.azurecr.io/url-shortener:latest

  - stage: Deploy
    condition: |
      and(
        succeeded(),
        or(
          eq(variables['Build.SourceBranch'], 'refs/heads/main'),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        )
      )
    jobs:
      - job: DeployToAzure
        displayName: 'Deploy To Azure'
        steps:
          - task: AzureContainerApps@1
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              containerAppName: 'shortit-app'
              resourceGroup: 'url-shortener-rg'
              imageToDeploy: 'shortitacr.azurecr.io/url-shortener:$(Build.SourceVersion)'

